/**
 * send-paystubs — emails each employee their quincenal paystub.
 *
 * POST { period_id }  (owner/admin only; JWT verified).
 * Reads the frozen snapshot (prepay_lines) for a LOCKED period + each employee's
 * personal_email, builds a paystub HTML, and emails it.
 *
 * Email transport:
 *   - PROD: Gmail SMTP (GMAIL_USER / GMAIL_APP_PASSWORD) — same as send-eod-digest.
 *   - LOCAL: if Gmail creds are absent, sends to the local Mailpit catcher
 *     (host.docker.internal:54325) so nothing hits real inboxes while testing.
 */

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SMTPClient } from "https://deno.land/x/denomailer@1.6.0/mod.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const GMAIL_USER = Deno.env.get("GMAIL_USER") ?? "";
const GMAIL_APP_PASSWORD = Deno.env.get("GMAIL_APP_PASSWORD") ?? "";
const FROM = GMAIL_USER || "payroll@joi.local";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const peso = (n: number) =>
  "MX$" + Number(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function paystubHtml(name: string, periodCode: string, range: string, l: Record<string, number>): string {
  const row = (label: string, val: number, sign = "") =>
    `<tr><td style="padding:6px 0;color:#374151;">${label}</td><td style="padding:6px 0;text-align:right;font-variant-numeric:tabular-nums;">${sign}${peso(val)}</td></tr>`;
  return `<!DOCTYPE html><html><body style="margin:0;padding:24px;background:#F3F4F6;font-family:-apple-system,Segoe UI,Arial,sans-serif;">
  <div style="max-width:520px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #e5e7eb;">
    <div style="background:#0f1e3d;padding:20px 28px;">
      <p style="margin:0;color:#f59e0b;font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;">JOI · Paystub</p>
      <h1 style="margin:6px 0 0;color:#fff;font-size:18px;">${name}</h1>
      <p style="margin:4px 0 0;color:#94a3b8;font-size:13px;">${periodCode} · ${range}</p>
    </div>
    <div style="padding:20px 28px;">
      <table style="width:100%;font-size:14px;border-collapse:collapse;">
        ${row("Base (½ month)", l.base)}
        ${row("Missed days", l.missed_deduction, "−")}
        ${row("Makeup credit", l.makeup_credit, "+")}
        ${row("Sunday premium", l.sunday_pay, "+")}
        ${row("Vacation premium", l.vacation_premium, "+")}
        ${row("Overtime", l.overtime_pay, "+")}
        ${row("Spiff", l.spiff_mxn, "+")}
        <tr><td colspan="2" style="border-top:1px solid #e5e7eb;padding-top:8px;"></td></tr>
        <tr><td style="padding:8px 0;font-weight:700;font-size:16px;color:#1d4ed8;">Net pay</td>
            <td style="padding:8px 0;text-align:right;font-weight:700;font-size:16px;color:#1d4ed8;">${peso(l.net)}</td></tr>
      </table>
    </div>
    <div style="padding:12px 28px;border-top:1px solid #e5e7eb;background:#f9fafb;">
      <p style="margin:0;font-size:11px;color:#9ca3af;">Gross (before taxes). System-generated by JOI Payroll.</p>
    </div>
  </div></body></html>`;
}

const USE_GMAIL = Deno.env.get("PAYSTUB_SMTP") === "gmail"; // prod: D sets this to "gmail"
const LOCAL_HOST = Deno.env.get("LOCAL_SMTP_HOST") ?? "supabase_inbucket_jpaihltkrohdqkqlbqkf";
const LOCAL_PORT = Number(Deno.env.get("LOCAL_SMTP_PORT") ?? "1025");

// Minimal plaintext SMTP straight to the local Mailpit catcher (no auth, no TLS).
async function sendLocalSmtp(to: string, subject: string, html: string) {
  const conn = await Deno.connect({ hostname: LOCAL_HOST, port: LOCAL_PORT });
  const enc = new TextEncoder();
  const dec = new TextDecoder();
  const buf = new Uint8Array(4096);
  const read = async () => { const n = await conn.read(buf); return dec.decode(buf.subarray(0, n ?? 0)); };
  const cmd = async (s: string) => { await conn.write(enc.encode(s + "\r\n")); return read(); };
  await read();
  await cmd("EHLO joi.local");
  await cmd(`MAIL FROM:<${FROM}>`);
  await cmd(`RCPT TO:<${to}>`);
  await cmd("DATA");
  const message =
    `From: JOI Payroll <${FROM}>\r\nTo: ${to}\r\nSubject: ${subject}\r\n` +
    `MIME-Version: 1.0\r\nContent-Type: text/html; charset=utf-8\r\n\r\n${html}\r\n.`;
  await cmd(message);
  await cmd("QUIT");
  conn.close();
}

function gmailClient() {
  return new SMTPClient({
    connection: { hostname: "smtp.gmail.com", port: 465, tls: true, auth: { username: GMAIL_USER, password: GMAIL_APP_PASSWORD } },
  });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    const token = (req.headers.get("Authorization") ?? "").replace("Bearer ", "");
    const authClient = createClient(SUPABASE_URL, Deno.env.get("SUPABASE_ANON_KEY") ?? "", {
      global: { headers: { Authorization: `Bearer ${token}` } },
    });
    const { data: userData } = await authClient.auth.getUser();
    const uid = userData.user?.id;
    if (!uid) return new Response(JSON.stringify({ error: "Not authenticated" }), { status: 401, headers: cors });

    const admin = createClient(SUPABASE_URL, SERVICE_ROLE);
    const { data: profile } = await admin.from("user_profiles").select("role").eq("id", uid).maybeSingle();
    if (!profile || !["owner", "admin"].includes(profile.role)) {
      return new Response(JSON.stringify({ error: "Owner/admin only" }), { status: 403, headers: cors });
    }

    const { period_id } = await req.json();
    if (!period_id) return new Response(JSON.stringify({ error: "period_id required" }), { status: 400, headers: cors });

    const { data: period } = await admin
      .from("payroll_periods")
      .select("period_code, start_date, end_date")
      .eq("id", period_id)
      .maybeSingle();
    const range = period ? `${period.start_date} – ${period.end_date}` : "";

    const { data: lines, error } = await admin
      .from("prepay_lines")
      .select("net, base, missed_deduction, makeup_credit, overtime_pay, sunday_pay, vacation_premium, spiff_mxn, employees(full_name, personal_email)")
      .eq("period_id", period_id);
    if (error) throw error;

    const gmail = USE_GMAIL ? gmailClient() : null;
    let sent = 0;
    const skipped: string[] = [];
    for (const l of lines ?? []) {
      const emp = (l as Record<string, unknown>).employees as { full_name: string; personal_email: string | null } | null;
      const to = emp?.personal_email;
      if (!to) { skipped.push(emp?.full_name ?? "unknown"); continue; }
      const subject = `Tu pago — ${period?.period_code ?? "periodo"}`;
      const html = paystubHtml(emp!.full_name, period?.period_code ?? "", range, l as Record<string, number>);
      if (gmail) {
        await gmail.send({ from: `"JOI Payroll" <${FROM}>`, to, subject, html });
      } else {
        await sendLocalSmtp(to, subject, html);
      }
      sent++;
    }
    if (gmail) await gmail.close();

    return new Response(JSON.stringify({ sent, skipped_count: skipped.length, skipped }), {
      headers: { ...cors, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("send-paystubs error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : String(e) }), {
      status: 500,
      headers: { ...cors, "Content-Type": "application/json" },
    });
  }
});
