// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hipxsmawxvlxjzotsgfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcHhzbWF3eHZseGp6b3RzZ2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNjEzNTEsImV4cCI6MjA5MDYzNzM1MX0.nBGHv4nFy_EyfcM8vbScGWzRhbzeL7zKrQAZ-tCxUDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});